name: Deploy to Amazon Lightsail

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: LightSail

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    #배포 자동화를 시작합니다.
    - name: 배포 자동화
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.LIGHTSAIL_HOST }}
        username: ${{secrets.LIGHTSAIL_USERNAME}}
        key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
        source: 'mlb-server/*'
        strip_components: 1
        target: '/home/ubuntu/mlb-server/'
        
    - name: Check files in workspace
      run: ls -lah
      
    - name: Transfer Deploy Script use SCP
      uses: appleboy/scp-action@master
      with:
        username: ${{secrets.LIGHTSAIL_USERNAME}}
        host: ${{ secrets.LIGHTSAIL_HOST }}
        key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
        source: "mlb-server/deploy.sh"
        target: "/home/ubuntu/mlb-server"

    # - name: 서버 스크립트 실행
    #   uses: appleboy/ssh-action@master
    #   with:
    #     username: ubuntu
    #     host: ${{ secrets.LIGHTSAIL_HOST }}
    #     key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
    #     script_stop: true
    #     script: |
    #       # blog 디렉토리로 이동
    #       cd mlb-server
          
